### PR TITLE
Change agent data pre-processing

### PR DESCRIPTION
**Pull request by atte-wsp**
Previously agent data has been combined in data pre-processing before plotting. However, this does not work if analysis is not based on predefined groups. 

Move group/combine to plotting scripts and data pre-processing includes only cleaning and defining variables :
* Change combine_agent_data. R to tidy_agent_data.R. Use Rdata files to save data frames for different scenarios.
* Group agent data tables in plotting scripts

PR also removes car access from zones plotting as this result is no longer produced by Helmet-model.

### CODE REVIEW

**Review by johpiip — COMMENTED** [review]
Hey! Sorry for late review. Could you upload `V2030_ve0_rm/agents.txt` in Teams so that I can test this? I am getting some weird errors and I wish to make sure it is not because of the input file. :) That file is references in `config.yml`.

**Comment by atte-wsp** [comment]
Sure! Sorry I forgot that already changed column names of input data. 

I've later changed the input data to have two tables `agents ` and `tours`.  This requires further updates to R scripts. Would you prefer that I add those changes here as well, or should I make a new PR?

**Comment by johpiip** [comment]
@atte-wsp Hmm, you can add it here since it is further "changing agent data preprocessing". :) I'll review this once you've pushed new commits and uploaded the `V2030_ve0_rm` data.

**Comment by atte-wsp** [comment]
@johpiip Helmet data is updated to Sharepoint folders and changes are added here.

**Comment by atte-wsp** [comment]
@johpiip Seems that some refactoring of code is still needed as calculation is quite complicated and slow after latest changes. I'll comment here when done.

**Comment by johpiip** [comment]
No problem, I will wait until you are done, @atte-wsp! :)

**Comment by johpiip** [comment]
Hey @atte-wsp, sorry to bug you, but I glanced through some of your code. As a pre-review comment, could you `Ctrl+Shift+F` for `library(sf)` calls, and edit them so that you *first* call `library(tidyverse)` and *then* `library(sf)`? And could check that the results stay the same? `sf` docs recommend that particular order: https://r-spatial.github.io/sf/reference/tidyverse.html If the coordinates cause problems, you can `sf::st_drop_coordinates()` before using `dplyr` verbs.

**Comment by atte-wsp** [comment]
Data pre-processing is ready for review. I'll add another branch for plotting as there are tons of updates coming with new effects and removing / updating old ones.

**Review by johpiip — APPROVED** [review]
Great work! All scripts can be run on my laptop too.

**Pull request merged**
