### PR TITLE
Update pkgs with R v4.3.0

### PR DESCRIPTION
**Pull request by johpiip**
This PR updates R version to 4.3.0 and updates all packages to their latest versions. This PR also removes dependency to MRAN package repository as it is being deprecated. Updating packages mean several adaptations to dependencies, such as:
- renv code in automatically updated
- replacing size with linewidth when plotting lines
- specifying crs explicitly in new point data
- filtering with vectors instead of one-column matrices
- adding explicit argument names
- adding explicit legend naming

Results were compared numerically and plots were compared visually.

Accessibility results were not yet compared as we are missing the "before" data due to performance issue. Working on it though!

### CODE REVIEW

**Comment by johpiip** [comment]
Lifecycle warnings:

In `scripts/basemap/centers_uusimaa-2050.R:9`:

```
Warning:
Using one column matrices in `filter()` was deprecated in dplyr 1.1.0.
ℹ Please use one dimensional logical vectors instead.
```

In `scripts/figures/links.R:64`:
```
Warning:
Specifying the `id_cols` argument by position was deprecated in tidyr 1.3.0.
ℹ Please explicitly name `id_cols`, like `id_cols = fid`.
```

**Comment by johpiip** [comment]
Also this parsing issue, but this may be old and refer to missing columns in syöttödata. I have not yet identifies the data frame.
```
Warning: One or more parsing issues, call `problems()` on your data frame for details, e.g.:
  dat <- vroom(...)
  problems(dat)
```

**Comment by johpiip** [comment]
Warnings on comments before this were fixed.

**Review by hsl-petrhaj — APPROVED** [review]
Not that I understand everything, but if it worked, it worked.

**Pull request merged**
